apiVersion: v1
kind: Service
metadata:
  name: sample-service
  annotations:
    ## Instances Targets
    #service.beta.kubernetes.io/aws-load-balancer-type: nlb
    ## To deploy a load balancer to a private subnet, must have the following annotation:
    # service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    ## IP Targets
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: nginx